#! /bin/csh -f

set startnum="1"

set obsname="ngc302"
set obsfilename="NGC3603-02"

while ($startnum<200)

if($startnum<10) then
	set scan="scan$startnum"
	set offscan="offscan$startnum"

else if($startnum<100) then
	set scan="scan$startnum"
	set offscan="offscan$startnum"

else if($startnum<1000) then
	set scan="scan$startnum"
	set offscan="offscan$startnum"

else
	set scan="scan$startnum"
	set offscan="offscan$startnum"

endif

/home/oper/autocorrelator/autocorrelator -v -f Mark5B-128-4-2 /media/data1/30MObs/$obsfilename/$obsname\_wa_$scan.m5a -dump /media/data1/30MObs/$obsfilename/$obsname\_wa_$scan.txt -d /nu -a 13 -b 2

/home/oper/autocorrelator/autocorrelator -v -f Mark5B-128-4-2 /media/data1/30MObs/$obsfilename/$obsname\_wa_$offscan.m5a -dump /media/data1/30MObs/$obsfilename/$obsname\_wa_$offscan.txt -d /nu -a 13 -b 2

@ startnum = $startnum + 1

end
